version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: animate-community-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: animate-community
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
